[package]
name = "optimal"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde", "ndarray/serde", "rand_xoshiro/serde1"]

[dependencies]
blanket = { git = "https://github.com/JustinLovinger/blanket.git", branch = "develop" }
derive_more = "0.99"
lazy_static = "1.4.0"
ndarray = "0.15"
ndarray-rand = "0.14"
num-traits = "0.2"
once_cell = "1.17.1"
paste = "1.0.11"
rand = "0.8"
rand_xoshiro = "0.6.0"
replace_with = "0.1"
serde = { version = "1", features = ["derive"], optional = true }
streaming-iterator = "0.1"
thiserror = "1.0.40"

[dev-dependencies]
proptest = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.96"
static_assertions = "1.1.0"
test-strategy = "0.2.1"
