[workspace]
members = [
  "default-for",
  "derive-bounded",
  "optimal-pbil",
  "optimal-steepest",
]

[package]
name = "optimal"
version = "0.1.0"
edition = "2021"
authors = ["Justin Lovinger"]
description = "Mathematical optimization and machine learning framework and algorithms"
repository = "https://github.com/justinlovinger/optimal-rs"
readme = "README.md"
keywords = ["ai", "machine-learning", "optimization"]
categories = ["science", "mathematics"]
license = "MIT"

[badges]
github = { repository = "justinlovinger/optimal-rs", workflow = "build" }

[dependencies]
blanket = "0.3.0"
streaming-iterator = "0.1"

[dev-dependencies]
ndarray = "0.15"
optimal-pbil = { path = "optimal-pbil" }
paste = "1.0.11"
replace_with = "0.1"
serde_json = "1.0.96"
serde = { version = "1", features = ["derive"] }
static_assertions = "1.1.0"
