[workspace]
members = [
  "default-for",
  "derive-bounded",
  "optimal-core",
  "optimal-pbil",
  "optimal-steepest",
]

[package]
name = "optimal"
version = "0.1.0"
edition = "2021"
authors = ["Justin Lovinger"]
description = "Mathematical optimization and machine learning framework and algorithms"
repository = "https://github.com/justinlovinger/optimal-rs"
readme = "README.md"
keywords = ["ai", "machine-learning", "optimization"]
categories = ["science", "mathematics"]
license = "MIT"

[badges]
github = { repository = "justinlovinger/optimal-rs", workflow = "build" }

[dependencies]
optimal-core = { path = "optimal-core" }

[dev-dependencies]
ndarray = "0.15.6"
optimal-pbil = { path = "optimal-pbil" }
