[package]
name = "optimal"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde", "ndarray/serde"]

[dependencies]
derive_more = "0.99"
ndarray = "0.15"
ndarray-rand = "0.14"
num-traits = "0.2"
paste = "1.0.11"
rand = "0.8"
replace_with = "0.1"
serde = { version = "1", features = ["derive"], optional = true }
streaming-iterator = "0.1"

[dev-dependencies]
proptest = "1"
test-strategy = "0.2.1"
