#!/bin/sh

cargo readme -o README.md
cargo readme -r derive-num-bounded -o README.md
cargo readme -r optimal-binary -o README.md
cargo readme -r optimal-linesearch -o README.md
cargo readme -r optimal-pbil -o README.md

git add README.md
git add **/README.md
